# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_crushist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_votes',
            new_name='votes',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_url',
            new_name='yt_url',
        ),
    ]
